# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timshadel.com" # the base hostname & protocol for your site
title: Zdot
subtitle: Thinking out loud, in color.
description: A blog and podcast about technology and family.


# PLUGINS
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap


# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Tim Shadel
  avatar: avatar.jpg
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h2>Thinking out loud, in color.</h2>
  header_text_feature_image: img/blog-header.jpg
  footer_text: >
     <p>Find an error? File an <a href="https://github.com/timshadel/timshadel.github.io/issues/">issue</a> or open a <a href="https://github.com/timshadel/timshadel.github.io/tree/master/_posts">PR</a>.</p>

  # Icons
  rss: true
  feedly: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "timshadel"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/timshadel"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "http://stackoverflow.com/users/1330722/tim-shadel"
  steam:
  tumblr:
  twitter: "timshadel"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-167784-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: timshadel
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Older"
  str_prev: "Newer"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic|Inconsolata:400,700|Merriweather:300,400,700,300italic,400italic,700italic"

  # Post navigation
  post_navigation: false


# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

permalink: "none"
excerpt_separator: "<!--more-->"


# PODCAST: Used to generate the iTunes-compatible RSS feed
podcast:
  owner:
    name: Tim Shadel
    email: timshadel@gmail.com
  explicit: "no" # Change to yes if you're a potty mouth
  image: /img/generic-2000.png # iTunes requires 2,000 pixel art
  keywords: "java,ruby,ios,swift"
  categories:
    - category: "Technology"


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
